### ISSUE TITLE
Custom domain support

### ISSUE THREAD

**Issue by and-selmo** [jamesward/sf-cors-proxy#1]
Unable to connect to a salesforce custom domain using this sf-cors-proxy.

For example xxxxx.my.salesforce.com, will give an error in the requests when attempting to make a query. It works perfectly using any regular salesforce environment.

I have the assumption of the custom domain masking the salesforce instance that the proxy requires to make its queries to.

**Comment by jamesward** [comment]
Do you know if your org allows logins from `login.salesforce.com`?

**Comment by and-selmo** [comment]
No it does not, I had changed your code to target the custom domain for the
login url.

**Comment by jamesward** [comment]
I'm testing this locally and even though I've disabled logins from `login.salesforce.com` I'm still able to login via `https://login.salesforce.com/services/oauth2/userinfo?oauth_token=$token` which seems weird.   So I'm not sure what the problem is.  By chance is this a Sandbox org?

**Comment by and-selmo** [comment]
This is a sandbox org, we tried the test.login.com as well. So I was not sure if the fact that it was a sandbox as well as a custom domain was causing the issue.

**Comment by jamesward** [comment]
Ah, this is definitely due to it being a sandbox.  Let me add support for sandboxes.  Stand by.

**Comment by and-selmo** [comment]
Thank you I really appreciate how quickly you responded and all the extra effort you are putting in!

**Comment by jamesward** [comment]
This should be deployed in about 10 minutes.  Reopen this if it still isn't working for you.
