### ISSUE TITLE
Sandbox domain

### ISSUE THREAD

**Issue by rafaelgallani** [jamesward/sf-cors-proxy#2]
Im not being able to send the requests via sandbox. I've already tried in a custom org and in a production one, and in both tries the result was successful.

When trying to POST to sandbox ORG, what I get is this: 
![image](https://cloud.githubusercontent.com/assets/18705930/17631625/38bb8e08-609b-11e6-91fd-2217f09f9fac.png)

Thanks!

**Comment by jamesward** [comment]
I'm trying to reproduce this and I haven't been able to.  Did this request work against `test.salesforce.com` but not against `sfdc-cors.herokuapp.com` ?

**Comment by jamesward** [comment]
I was able to reproduce this!  A fix should be deployed in about 10 minutes.  Let me know how it goes.
